service: weather-ml-fiap
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 128
  timeout: 30

  environment:
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID} 
    S3_BUCKET_NAME: s3-lab3-lucas
    API_KEY: ${env:API_KEY}

  iam:
    role: arn:aws:iam::${self:provider.environment.AWS_ACCOUNT_ID}:role/LabRole

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**

custom:
  pythonRequirements:
      useStaticCache: false
      useDownloadCache: false
      pipCmdExtraArgs:
        - "--implementation cp"
        - "--only-binary=:all:"
        - "--upgrade"

functions:
  collectWeatherLiveData:
    handler: collect_weather/live_data.lambda_handler
    events:
      - schedule: rate(1 hour)

  collectWeatherHistoricalData:
    handler: collect_weather/historical_data.lambda_handler
    events:
      - http:
          path: "historical"
          method: "get"
          cors: true

  trainModel:
    handler: train_model/model.lambda_handler
    timeout: 600
    memorySize: 1024
    events:
      - schedule: cron(0 3 * * ? *)